# -*- coding: utf-8 -*-
"""ChatBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aTwXndSSTujNn_67SLa3bpZq8jm_7Az5
"""

!pip install nltk

import nltk
from nltk.chat.util import Chat, reflections

pairs = [
    [
        r'hi|hey|hello',
        ['Hello', 'Hi', 'Chatbot welcomes you']
    ],
    [
        r'how are you|are you fine|what\'s happening',
        ['Feeling good', 'Going good', 'Fine']
    ],
    [
        r'tell about you|introduce yourself|may i know about you',
        ['I am ChatBot, an AI assistant for Pavithira']
    ],
    [
        r'what next|next plan|then',
        ['Just go with the flow', 'Be scheduled to list', 'Nothing much']
    ],
    [
        r'favorite place|what\'s your favourite|hobby',
        ['Learning', 'Exploring more and more', 'Travelling']
    ],
    [
        r'bye|let\'s end|thank you',
        ['Goodbye', 'Bye', 'Good to see you']
    ]
]

chatbot = Chat(pairs, reflections)

while True:
    user_input = input('You: ')
    if user_input.lower() in ['bye', 'exit', 'quit']:
        print('ChatBot: Goodbye!')
        break
    response = chatbot.respond(user_input)
    print('ChatBot:', response if response else "Sorry, I didn't understand that.")